name: ci

trigger:
  manual: true

steps:
  - name: check
    env: .moira/envs/rust.nix
    run: cargo check --workspace
    network: true

  - name: test
    env: .moira/envs/rust.nix
    run: cargo test --workspace
    depends_on: [check]
    network: true
